title: "Marc Bruna Fuster"
tagline: "El teu fuster al Pallars Sobirà"
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
author: "Recrea't"
url: "https://marcbruna.cat"
logo: "/assets/img/Logo.svg"

email: "info@marcbruna.cat"
phone:
  number: 34600000000
  title: "(+34) 600 000 000"
address: "Street XXX, 08080 City"

social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

google_analytics: UA-111111111-1

twitter:
  username:
  title: "Follow us on Twitter"
  card: summary #keep this to generate a twitter share card
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234
  title: "Follow us on Facebook"
gmaps:
  id: 1234

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

serveis:
  - Portes
  - Finestres
  - Cuines
  - Mobles a mida
  - Parquets
  - Fusteria en general
